required = [
  "k8s.io/code-generator/cmd/client-gen",
  # needed by generated clientsets, but not an explicit dep in client-gen itself
  "k8s.io/apimachinery/pkg/apimachinery/registered",

  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  name="k8s.io/client-go"
  version="v7.0.0"

[[constraint]]
  name="k8s.io/api"
  version = "kubernetes-1.10.0"

[[constraint]]
  name="k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[override]]
  name="k8s.io/kubernetes"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "github.com/openshift/generic-admission-server"
  revision = "76d182e57ce628bbf6eb266a7d26cf6c52adf551"
